version: "3"000000000
services:
    app:
        build: ./flask
        restart: always
        links:
            - bd
        depends_on:
            - bd
        ports:
            - "5000:5000"
    frontend:
        build: ./frontend-glo2005
        container_name: frontend
        ports:
            - "8080:8080"
        depends_on:
          - app
        environment:
            PORT: 8080
    bd:
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: glo2005
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./mysql/bd_init/:/docker-entrypoint-initdb.d:ro
        ports:
            - "3306:3306"