CREATE DATABASE IF NOT EXISTS glo2005 CHARACTER SET utf8;

USE glo2005;

CREATE TABLE IF NOT EXISTS Users(id INTEGER NOT NULL AUTO_INCREMENT,
 username VARCHAR(64) NOT NULL UNIQUE,
 hashedPassword VARCHAR(60) NOT NULL,
 PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS Artists(artist_id INTEGER NOT NULL AUTO_INCREMENT,
artist_name VARCHAR(64) NOT NULL,
years_active INTEGER,
PRIMARY KEY (artist_id));

CREATE TABLE IF NOT EXISTS Genres(genre_id INTEGER NOT NULL AUTO_INCREMENT,
 name VARCHAR(64) NOT NULL UNIQUE,
 PRIMARY KEY (genre_id));

CREATE TABLE IF NOT EXISTS Albums(album_id INTEGER NOT NULL AUTO_INCREMENT,
 title VARCHAR(64) NOT NULL,
 year INTEGER NOT NULL,
 artist_id INTEGER,
 genre_id INTEGER,
 PRIMARY KEY (album_id),
 FOREIGN KEY(artist_id) REFERENCES Artists(artist_id),
 FOREIGN KEY(genre_id) REFERENCES Genres(genre_id));


CREATE TABLE IF NOT EXISTS Songs(song_id INTEGER NOT NULL AUTO_INCREMENT,
 album_id INTEGER, title VARCHAR(64) NOT NULL,
 duration INTEGER NOT NULL,
 PRIMARY KEY (song_id),
 FOREIGN KEY (album_id) REFERENCES Albums(album_id));

